name: flutterfp25
description: A new Flutter project.
publish_to: 'none'   # Remove this line if you ever want to publish

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ── Assets ───────────────────────────────────────────────────
  # Place logo.png in <project‑root>/images/  (not inside /lib).
  # Add more assets here as needed.
  assets:
    - images/logo.png
    - images/sweatshirt.png
    - images/sweatpants.png
    - images/hoodie.png
    - images/jacket.png
    - images/hoodie2.png
    - images/sweatpantsgrey.png
    - images/polo.png
    - images/sweatshirtgreen.png
    - images/hoodie3.png
    - images/quarterzip.png

  



